[supervisord]
nodaemon=true

[program:init_admin_password]
command=python docker/multi_service/init_admin_password.py
autostart=true
autorestart=false
startretries=3
stdout_logfile=/var/log/supervisor/init_admin_password.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/supervisor/init_admin_password_err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5

[program:migrations]
command=python docker/multi_service/migrations.py
autostart=true
autorestart=false
startretries=3
stdout_logfile=/var/log/supervisor/migrations.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/supervisor/migrations_err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5

[program:import_documents_to_vdb]
command=python docker/multi_service/import_documents_to_vdb.py
autostart=true
autorestart=false
startretries=3
stdout_logfile=/var/log/supervisor/import_documents_to_vdb.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/supervisor/import_documents_to_vdb_err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5

[program:api]
command=python app.py
autostart=true
autorestart=true
startretries=3
stdout_logfile=/var/log/supervisor/api.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/supervisor/api_err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5

[program:websocket]
command=python websocket.py
autostart=true
autorestart=true
startretries=3
stdout_logfile=/var/log/supervisor/websocket.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/supervisor/websocket_err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5

[program:roundtable]
command=python task/chatroom_run.py
autostart=true
autorestart=true
startretries=3
stdout_logfile=/var/log/supervisor/roundtable.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/supervisor/roundtable_err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5

[program:workflow]
command=python task/workflow_run.py
autostart=true
autorestart=true
startretries=3
stdout_logfile=/var/log/supervisor/workflow.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/supervisor/workflow_err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5

[program:celery]
command=python celery_app.py
autostart=true
autorestart=true
startretries=3
stdout_logfile=/var/log/supervisor/celery.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/supervisor/celery_err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5